### ISSUE TITLE
Remove auto-scroll on page load

### ISSUE THREAD

**Issue by vivianspencer** [botui/botui#123]
We're currently using the Bot UI framework for a few projects where the bot is embedded in part of the page and provides resources to users.

The issue we're experiencing is that when the page loads, the bot is scrolled into view.

Is there any way to remove this functionality?

**Comment by ViLourenco** [comment]
Hey @vivianspencer, did you fix it?

**Comment by vivianspencer** [comment]
@ViLourenco Yes we managed to fix this by commenting out the following lines and running the script locally:

- https://github.com/botui/botui/blob/master/build/botui.js#L214-L215
- https://github.com/botui/botui/blob/master/build/botui.js#L221
