### ISSUE TITLE
 _botui.default is not a constructor while using parcel-bundler

### ISSUE THREAD

**Issue by IsaacHub** [botui/botui#139]
I'm using with `parcel`, I installed it through npm, here is the code:

```
import BotUI from 'botui'
import Vue from 'vue'

let botui = new BotUI('bot', {
  vue: Vue 
});
```

![Screenshot_23](https://user-images.githubusercontent.com/20126441/80087463-bce64a00-8578-11ea-91a0-fd682755cc50.png)

**Comment by moinism** [comment]
Hey, seems like parcel is resolving the module from the client side so the `BotUI` instance is available on `window` object.

You can use it like this for now:

```
import _botui from 'botui'
import Vue from 'vue'

let botui = new window.BotUI('bot', {
  vue: Vue
});
```

**Comment by IsaacHub** [comment]
Original issue gone, and thrown other error `You are using runtime build of vue` so I changed the vue import to 

`import Vue from 'vue/dist/vue.esm.js';`

It's fixed. Thanks.
