### ISSUE TITLE
Any plan to make it in Vanila JS?

### ISSUE THREAD

**Issue by Abhi0725** [botui/botui#140]
Hi 👋,

First of thanks for this awesome framework.

Do you have any plan to have it in Vanila JS?

**Comment by moinism** [comment]
hey, no plans yet but whats your use case?

**Comment by moinism** [comment]
hey @Abhi0725, actually the upcoming version will be entirely in vanilla js with no other dependencies.

**Comment by Abhi0725** [comment]
That would be great. Thanks a lot for this awesome framework Moin.

**Comment by megeek** [comment]
I would love this as well.  Any update on the status of this?  I'm loving the framework so far but would love to not have to pull in Vue as a dependency....

**Comment by mkmaker** [comment]
Are we going with vanila JS anytime soon?

**Comment by jeremielp** [comment]
Also interested in a vanila JS version. Seems like the project has been abandoned...

**Comment by softmonkeyjapan** [comment]
Same here, love it, perfect for my use case but the dependency with Vue isn't cool.
Last commit was on July 3rd 2020.
@moinism is the project not maintained anymore ?

**Comment by mkmaker** [comment]
Hey @moinism 

Thank you so much for the VanillaJS migration. May I know what is the status of that? Any expected release date?

Also, anything I can help in the migration let me know.

**Comment by moinism** [comment]
Just an update folks:
- The new version is in the branch: https://github.com/botui/botui/tree/v2/packages/botui
- Rewritten from scratch
- Can be used with any UI framework, React package available, Vue and Solid planned.
- Give it a try if you can, could use some help with testing
- Thank you!

**Comment by moinism** [comment]
Thank you all for waiting this long for the vanilla version. It has been finally been released. Go check it out.
