### ISSUE TITLE
Attribute "pattern" inside action.text

### ISSUE THREAD

**Issue by gianpaolo-lopresti-iol** [botui/botui#161]
Hi,
I think it might be useful to have a "pattern" field inside the action object, valid for the "input" html tag.
Given that the sub_type field exists, but without a pattern it is sometimes useless (as in the case of 'tel'), could we therefore insert a "pattern" field to be mapped with the relative "pattern" attribute of the html "input" tag?
I tried using the browser development tools to set the pattern attribute at run time and in my opinion it would be a useful feature.

Thanks for the attention,
Best regards.

**Comment by moinism** [comment]
Hey @gianpaolo-lopresti-iol, sorry for the late response.

With the v2 release, I believe this is possible now: https://docs.botui.org/react/actions#input
