### ISSUE TITLE
botui.action.select does not show dropdown

### ISSUE THREAD

**Issue by karyeun** [botui/botui#165]
i had the following code/setup. somehow, the dropdown does not show properly in the browser. 

`<!DOCTYPE html>
<html>

<head>
    <meta charset="utf-8">
    <title>BotUI - Hello World</title>
    <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/botui/build/botui.min.css" />
    <link rel="stylesheet" h
![Screenshot 2022-09-27 at 10 39 22 AM](https://user-images.githubusercontent.com/5344717/192418785-5012dab3-cbc8-4e69-ae5b-d5a122864968.png)
ref="https://cdn.jsdelivr.net/npm/botui/build/botui-theme-default.css" />
</head>

<body>
    <div class="botui-app-container" id="hello-world">
        <bot-ui></bot-ui>
    </div>
    <script src="https://cdn.jsdelivr.net/vue/latest/vue.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/botui/build/botui.js"></script>
    <script>
        var botui = new BotUI('hello-world');

        botui.message.add({
            content: 'Hello World from bot!'
        }).then(function () { // wait till previous message has been shown.

            botui.action.select({
                action: {
                    placeholder: "Select Language",
                    value: 'TR', // Selected value or selected object. Example: {value: "TR", text : "Türkçe" }
                    searchselect: true, // Default: true, false for standart dropdown
                    label: 'text', // dropdown label variable
                    options: [
                        { value: "EN", text: "English" },
                        { value: "ES", text: "Español" },
                        { value: "TR", text: "Türkçe" },
                        { value: "DE", text: "Deutsch" },
                        { value: "FR", text: "Français" },
                        { value: "IT", text: "Italiano" },
                    ],
                    button: {
                        icon: 'check',
                        label: 'OK'
                    }
                }
            }).then(function (res) { // will be called when a button is clicked.
                console.log(res.value); // will print "one" from 'value'
            });
        });
    </script>
</body>
</html>`

![Screenshot 2022-09-27 at 10 40 55 AM](https://user-images.githubusercontent.com/5344717/192419002-856ac93b-2ac6-41eb-9e3f-76d6968b3f30.png)

**Comment by moinism** [comment]
@karyeun this could be due to some problem in the library we're using for `.select`. We cannot work on the current version of BotUI because there's a new version in progress and near completion. If you're just starting to implement BotUI in your project, I suggest you wait for a week and then use the new version. If you're feeling adventurous, however, you can already go ahead and try the new version (with React):
https://github.com/botui/botui/tree/v2

**Comment by karyeun** [comment]
thank you for your info, moinism. appreciated & looking forward to the updated version.
