### ISSUE TITLE
Are links working?

### ISSUE THREAD

**Issue by ReemAbdelRahman** [botui/botui#167]
**Describe the bug**
I am using the [links](https://docs.botui.org/react/messages#links) as in the documentation, but they do not seem to work correctly

```
const App = () => {
  useEffect(() => {
    mybot.message.add(
      {
        links: [
          {
            text: 'another url',
            href: 'https://www.google.de/',
          },
        ],
      },
      { messageType: 'links' }
    )
  }, [])

  return (
    <div>
      <BotUI bot={mybot}>
        <BotUIMessageList />
        <BotUIAction />
      </BotUI>
    </div>
  )
}
```

**Expected behavior**
I am expecting a clickable link, but I am getting a normal message text "links" not even "another url".

**Screenshots**
![image](https://user-images.githubusercontent.com/51020016/199301694-653b4c82-b389-44a6-8014-ab5a4468620d.png)

**Comment by moinism** [comment]
@ReemAbdelRahman which version of [`@botui/react`](https://www.npmjs.com/package/@botui/react) package are you using? I just verified with `v1.1.5` and it seems to be rendering the links just fine.

**Comment by ReemAbdelRahman** [comment]
@moinism Thank you for your reply! I am using `v1.1.1` as I used the [quickstart example ](https://github.com/botui/react-quickstart)
I have just tried `v1.1.5` and links are working now.
