### ISSUE TITLE
Is there a way to assign onChange event to the action textbox

### ISSUE THREAD

**Issue by manik-ushur** [botui/botui#171]
**Is your feature request related to a problem? Please describe.**
I am trying to bring up the iPhone conversations like UI, where I want to show an up arrow in place of Done button. This is doable. The issue is that I require the up arrow should be grey when the action text box is empty, but should turn blue as the user starts typing.

**Describe the solution you'd like**
If there is an event handle for the text box, I can attach to it to update the icon as the user starts typing.

**Describe alternatives you've considered**
Add the event handle by using document.addEventListener, but does not look like a optimal option and can effect performance as well

**Comment by moinism** [comment]
Hey,

I think you'll have to implement a custom `action` to achieve that. Please follow this guide: https://docs.botui.org/react/custom
