### ISSUE TITLE
Time stamp

### ISSUE THREAD

**Issue by manik-ushur** [botui/botui#177]
**Is your feature request related to a problem? Please describe.**
I am not able to show the time stamp of the messages in the history

**Describe the solution you'd like**
iPhone messaging shows time of the conversation. I am not able to do it using bot ui

**Describe alternatives you've considered**

**Additional context**
![image](https://user-images.githubusercontent.com/48345140/212689304-18243347-69ce-4ddb-9b0d-184156d49f6a.png)

**Comment by moinism** [comment]
This is not something that BotUI supports natively (nor do I plan to add it anytime soon), but you can show whatever metadata you like with custom logic.

**Comment by manik-ushur** [comment]
Thanks Moin. Appreciate..
