### ISSUE TITLE
Multiple lines

### ISSUE THREAD

**Issue by jessekahner** [botui/botui#22]
Is it possible to have multiple lines inside of a message?

Either by using a `<br>`  or directly in the message?

Thanks!

**Comment by ignatandrei** [comment]
Same here ;-)

**Comment by nickdunn** [comment]
Definitely. I can't currently put HTML in a message (unless I'm doing it wrong), and I'd really like to!

**Comment by moinism** [comment]
Hey guys, I've just tried it with HTML in message and it works. [Here's a fiddle](https://jsfiddle.net/ww83kafa/). 
What problem are you facing?

**Comment by nickdunn** [comment]
The HTML is removed when I add buttons to the message. Here's an example showing buttons appearing after a delay. https://jsfiddle.net/r6khd11u/

**Comment by moinism** [comment]
Ahh. This is Vue messing up again. Please use `v2.0.5` of Vue.js, if possible.
https://jsfiddle.net/27L4osmz/

**Comment by nickdunn** [comment]
Confirmed, works with Vue 2.0.5, but 2.3.* or 2.4.* doesn't work. Thanks for your help!

**Comment by jessekahner** [comment]
Guys (and gals), I don't want to seem pessimistic, but if something doesn't _seem_ to work in a more recent release of Vue, why would this project (pretty recent) depend on an older version of Vue?

**Comment by manik-ushur** [comment]
Is this issue closed in the latest release as well? I could see that we can add embed, image, links. But, is there a way to add custom html/scripts?
