### ISSUE TITLE
AutoHide is not working properly in action button

### ISSUE THREAD

**Issue by javeedrahman** [botui/botui#23]
Hi guys,

i am using autohide to hide the button after the clicking, i am following the docs. but its not working properly

```javascript
botui.action.button({
  autoHide: false,
  action: [
    {
      text: 'One',
      value: 'one'
    }
  ]
}).then(function (res) { // will be called when a button is clicked.
  botui.action.hide(); // hide the button whenever you want.
});
```

Please help, Thanks in advance

**Comment by moinism** [comment]
Hey @javeedrahman 

Its working for me. Try [this fiddle](https://jsfiddle.net/sraonew8)

**Comment by javeedrahman** [comment]
Thank you @moinism :)
