### ISSUE TITLE
rendering an html div in botui div

### ISSUE THREAD

**Issue by kbimplis** [botui/botui#24]
I'm trying to embed an html div into a botui view. 

I want to embedd progress bar div, my bot is a survey interface and I want to show a progress bar for the user. So far, I can display the progress bar above or under the <bot-ui> </bot-ui> but not inside.
 
How would I go about embedding a div onto the bot view?

**Comment by moinism** [comment]
Hey @kbimplis,

I'd suggest you add it above or below BotUI. But if you still want to show inside then the only way is to add it inside message content. Try using Vue `v2.0.5`.
