### ISSUE TITLE
BotUI not loading in Internet Explorer

### ISSUE THREAD

**Issue by javeedrahman** [botui/botui#26]
Hi there,
Bot UI is not loading in the Internet Explorer. I have inspect element and i see <bot-ui></bot-ui>
is not generating the directive.

Any help please.

**Comment by bcks** [comment]
Internet Explorer 11 does not have native promise support, so you need to use a polyfill. This one got BotUI working in IE for me: https://github.com/stefanpenner/es6-promise

**Comment by javeedrahman** [comment]
@bcks thanks a lot, got it

**Comment by ViLourenco** [comment]
Hi,

There´s any customization in the code that I need to do or just add the lib to the app?
