### ISSUE TITLE
List of buttons

### ISSUE THREAD

**Issue by MarioDias17** [botui/botui#27]
Good afternoon, I would like the buttons to be displayed below each other as a list, currently they only stand side by side, I tried to use a cssClass, but it does not make changes to the button, I'm doing a faq bot and I'm using the buttons as object of the question, so if they appeared one below the other would facilitate, but since it is in the same array side by side, could help me in this matter? I'm using NodeJS

**Comment by moinism** [comment]
@MarioDias17 I'm hoping you've got some solution by now, sorry for responding late.

If you still need help, Please ask here: https://gitter.im/BotUIChat/botui
