### ISSUE TITLE
Feature Request

### ISSUE THREAD

**Issue by snowbreeze** [botui/botui#28]
1>Can we have a typing effect to make it more humanly

Example
https://i.giphy.com/media/m0hgeVAAFV6O4/source.gif

2>Can we autoplay embedded youtube video

**Comment by moinism** [comment]
1- Its already available [docs](https://docs.botui.org/guide.html#messages)
2- It's up to you, change the embed code to autoplay and it will.

**Comment by snowbreeze** [comment]
@moinism Thanks for the really quick response
Just wandering, i embeded the url like this, but how will i put the autoplay? Is custom html supported here?
```
  botui.message.add({
                type: 'embed', // this is 'text' by default
                content: 'https://www.youtube.com/embed/xxx'
            });
```
Also, is there a way to validate the inputs, something like jquery form validations

**Comment by snowbreeze** [comment]
Figured : 
'https://www.youtube.com/embed/XXX?rel=0&amp;showinfo=0;autoplay=true'
