### ISSUE TITLE
Cannot attach DOM with Pjax

### ISSUE THREAD

**Issue by mashirozx** [botui/botui#29]
Will which function BOT-UI call each time you refresh the page? I hope to add it to delay call of `pjax:popstate` , thank you ~

**Comment by moinism** [comment]
@mashirozx can you please provide a fiddle?

**Comment by mashirozx** [comment]
@moinism Sorry, don't understand what fiddle mean.
I want to do something like this:
```js
var pjaxInit = function(){
    some thing to call botui in new page...... this is what I want to known
}

$(document).on('pjax:popstate', function() {
    setTimeout(function(){
        pjaxInit();
    },500);
});
```
You may view my page in live: <https://2heng.xin/about/>

First you may click the logo to home page, then back to this page via the last tag in header, now you'll find botui not work.

I'd like to fix it with the code above. 

Thanks.

**Comment by mashirozx** [comment]
Problem has been solved, new to JavaScript...  @moinism  Thanks for your reply.😄
