### ISSUE TITLE
Incompatible with Vuejs 

### ISSUE THREAD

**Issue by maisnamraju** [botui/botui#30]
Hi, I tried the method listed in the docs to import it into a vuejs project but I was unsuccessful. Any tips on doing so ?

**Comment by moinism** [comment]
@maisnamraju can you explain the steps you took?
Maybe a jsfiddle?

**Comment by maisnamraju** [comment]
pasting the code here, using webpack with all the usual vuejs setup.  

```
<template>
    <div class="botui-app-container" id="hello-world">
      <bot-ui></bot-ui>
    </div>
</template>
<script> 
import Vue from 'vue'
import BotUI from 'botui'

export default {
 components: {
     BotUI // added this because without it, vue doesn't recognize the bot-ui element
 },
 mounted() {  
        var botui = new BotUI('hello-world', {
        vue: Vue 
        });

        botui.message.add({
        content: 'Hello World from bot!'
        });

        botui.message.add({
        human: true,
        content: 'Hello World from human!'
        });
}

}
</script>
```

**Comment by maisnamraju** [comment]
I have also tried using import BotUI on the import but that also throws out a bunch of different errors

**Comment by moinism** [comment]
@maisnamraju working example with Webpack is available here:
https://github.com/botui/botui-examples/tree/master/hello-world-webpack

**Comment by codedbyandrew** [comment]
You can use <bot-ui v-pre></bot-ui> or Vue.config.ignoredElements = ['bot-ui'] to allow your global Vue instance to ignore the child vue instance.

**Comment by maisnamraju** [comment]
thanks. didn't know about that one.

**Comment by rolandbkk** [comment]
anyone got it working? I´m getting the same errors...
