### ISSUE TITLE
AngularX integration

### ISSUE THREAD

**Issue by charlieboygis** [botui/botui#31]
First off all thank you for this nice library.
I'm trying to integrate it into an Angular4-CLI project but without success.
Can you give me some hints?

**Comment by denzelwamburu** [comment]
+1
👍🏿

**Comment by moinism** [comment]
It was built with only Vue in mind.
I haven't tested it with Angular so have no idea if it even works.

Try asking [here](https://gitter.im/BotUIChat/botui), someone might be able to help you.

**Comment by hajimurtaza** [comment]
@wamburu @moinism 
I feel angular is too big a framework to be excluded from using botui.
https://stackoverflow.com/questions/49724029/using-vue-components-in-angular-5

This is will allow you to use any external components in angular. I have just started , once i have a concrete example, Ill link it here
