### ISSUE TITLE
HTML tag

### ISSUE THREAD

**Issue by amauryleproux** [botui/botui#32]
Hi, first of all, well done, it's a really good bot! So thank you to share it with us.

It's not a real issue, I'm trying to add some html tag inside the text I display in response.
So basically I write this:

"Great! I know really well <b>" + res.value +"</b>!

But there is no bold text on the front end, do I need to add a function somewhere or my code sucks?

Thanks in advance.

**Comment by moinism** [comment]
Hey @amauryleproux,

Can you please provide a code example?

**Comment by amauryleproux** [comment]
Hello @moinism thanks for your reply here is an exemple:

The first time I refreshed the page I got the image I wanted but then I got nothing anymore, the HTML tag isn't loaded :/ 

Here is my code : 

.then(function(name){
   return botui.message.bot({
      loading: true,
      delay: 2500,
      content: "<img style='width:200px;height:200px;' src='/uploads/default/popup/AMAURY-02.png' alt='Guide MBA student'>"
    });
 })

**Comment by moinism** [comment]
Hey @amauryleproux,

Have a look at this: https://github.com/botui/botui/issues/7#issuecomment-315857326

**Comment by amauryleproux** [comment]
Thanks @moinism for your reply, even if I'm using this file:

https://cdn.jsdelivr.net/vue/latest/vue.min.js ?

it's not the right/latest version?

**Comment by moinism** [comment]
Yeah, its not.

Try not to use the version higher than `v2.0.7`. Latest is at `v2.3.2`

**Comment by amauryleproux** [comment]
Thank you very much @moinism that's work like a charm!
