### ISSUE TITLE
IE11 Troubles with ES6Promise

### ISSUE THREAD

**Issue by drlimbo** [botui/botui#39]
botui doesn't work in IE11 because of a problem with ES6Promise
`'Promise' is undefined`

_Latest Version with Webpack_

**Comment by flaviotsf** [comment]
Hi, I would try taking a look at referring the Promises polyfill in your project:

https://github.com/stefanpenner/es6-promise 

You mentioned you're using web pack - take a look at this answer:

https://stackoverflow.com/a/41062991

**Comment by merravid** [comment]
In botui.js look for the following:

    if(!root.Promise && !Promise && !options.promise) {
      loadScript(_esPromisePollyfill);
    }

and change it to:

    if(!root.Promise && typeof Promise === "undefined" && !opts.promise) {
      loadScript(_esPromisePollyfill);
    }

**Comment by moinism** [comment]
Thanks @merravid. Closing.
