### ISSUE TITLE
Adding two actions simultaneously overrides the first action

### ISSUE THREAD

**Issue by theEIC** [botui/botui#41]
Hey @moinism, thanks for the awesome framework!

I need to show a list of choices as action buttons and also display a text field below the list, allowing user input from either action (like in Google Assistant). When I try to add both actions though it is always the second action that is rendered inside the actions div, overriding the first action. Is it possible to do what I want to, have two actions render one below the other at the same time?

Also, if I could do that, what would be the best way to listen for input on both actions, since each would return a separate Promise?

**Comment by moinism** [comment]
Hey @theEIC, Thanks.

Unfortunately, it's not possible to achieve yet. The idea here is that only one action should be available at a time. As you can already see, presenting two actions would mean waiting for 2 different promises which makes it even more complex when there are more than 2.

So it doesn't support multiple actions at once. The only thing you can do for now is to show one after the other.

PS: Don't forget to add your bot to showcase 🙂
