### ISSUE TITLE
Question regarding generating dynamic actionable button

### ISSUE THREAD

**Issue by anikm1987** [botui/botui#44]
Hi,
Great framework. Its very easy to use. Thanks for sharing.
I have question regarding the actionable buttons. Is there any way you can add buttons dynamically may be based one result from the database?

Thanks for your help.

**Comment by nav1610** [comment]
Hi,

Even I have the same requirement, I tried to make the button data in a separate function and pass button data that string to button action. But it shows multiple empty buttons with no text on it.

Please comment if you had found out the solution.

Thank you

**Comment by batest12345** [comment]
Can you please provide me a code example with dynamic buttons using botui.

**Comment by mkmaker** [comment]
@nav1610 's answer is perfect.

@moinedgylabs I guess we can close this issue.

**Comment by moinism** [comment]
@mkmaker thanks.
