### ISSUE TITLE
html becomes text after action.text is used

### ISSUE THREAD

**Issue by jinho10** [botui/botui#49]
my server side returns html and it display when being sent, but when the action.text or bot is used at the frontend it becomes text. I did not look at the code, but clearly this is a bug.

**Comment by in-flu-ence** [comment]
I am facing a similar issue. Any img or link become text once action.text is used.

**Comment by moinism** [comment]
Can you guys share the version of Vue you are using?

**Comment by in-flu-ence** [comment]
I am using v2.3.2
https://cdn.jsdelivr.net/vue/latest

But it seems that the latest at vue.js website is v2.5.16
https://cdn.jsdelivr.net/npm/vue

**Comment by moinism** [comment]
So I think its related to #22. I should fix it soon.

But as a workaround, please follow this: https://github.com/botui/botui/issues/22#issuecomment-323194038

**Comment by msander1983** [comment]
This still seems to be an issue: 

`<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>test</title>
    <meta name="viewport" content="width=device-width, initial-scale=1" />
    <link rel="stylesheet" href="build/botui.min.css">
    <link rel="stylesheet" href="build/botui-theme-default.css">
</head>
<body>
    <div class="botui-app-container" id="hello-world">
        <bot-ui></bot-ui>
    </div>
    <script src="https://cdn.jsdelivr.net/npm/vue"></script>
    <script src="build/botui.js"></script>
    <script>
        var botui = new BotUI('hello-world');
        botui.message.add({
            delay: 500,
            loading: true,
            content: 'Hey there! What can I do to help?'
        }).then(start());
        function start() {
             botui.action.text({
                action: {
                    placeholder: 'Type your question here'
                },
                delay: 100,
            }).then(function (res) {
                if (res.value == "What is micro content?" || res.value == "Tell me about micro content") {
                    botui.message.add({
                        delay: 500,
                        loading: true,
                        type: 'text',
                        content: '<h1>Micro content</h1>Micro content is typically used for short, concise information in question-and-answer situations, such as chat bots. In Flare, micro content can be extracted from existing topics or created from scratch. For more information, see <a href="www.google.com">Google</a>',
                    }).then(function () {  start(); });
                } else {
                    botui.message.add({
                        delay: 300,
                        loading: true,
                        content: "I'm sorry! I don't know... Please ask ... :-)",
                    }).then(function () {  start(); });
                }
            })
        }



    </script>

</body>
</html>`

**Comment by dvolonnino** [comment]
Hi, this still seems to be an issue. Any fix?
