### ISSUE TITLE
chaining messages kills rich contents if not last in chain

### ISSUE THREAD

**Issue by alleherzen** [botui/botui#53]
Whenever I chain another message _after_ a message that contains any rich content (like links or images), the rich contents get deleted (images) and the links are removed and the message will just display the plain text instead. It is 100% reproducable.

`  homeBot.message.add({
    delay: 1000,
    content: 'some text'
  }).then(function () {
    return homeBot.message.add({
      delay: 1900,
      content: 'here some links:'
    });    
  }).then(function () {
    return homeBot.message.add({
      delay: 1600,
      content: '!(book) [Portfolio-PDF](https://www.alleherzen.de/downloads/Alleherzen_Portfolio.pdf) or visit the [Website](https://www.alleherzen.de).'
  }).then(function () {
    return homeBot.message.add({
      delay: 1600,
      content: 'some more text'
    });
  });
  });`

It can even be reproduced by just calling message add several times in a row like this:
` homeBot.message.add({
    delay: 1000,
    content: '!(book) [Portfolio-PDF](https://www.alleherzen.de/downloads/Alleherzen_Portfolio.pdf) or visit the [Website](https://www.alleherzen.de).'
  });

homeBot.message.add({
    content: 'some more text'
  });`

Any ideas on that issue? I am totally lost here.

**Comment by alleherzen** [comment]
I see - this is vue acting up again. You should probably update your docs though. I used your guide to embed the latest VUE version via CDN...

**Comment by yipcma** [comment]
@alleherzen  how did you resolve this issue? Same thing is happening to me, all the html line breaks / url are gone after a new message is pushed.

**Comment by yipcma** [comment]
resolved. Thanks @moinism

**Comment by drbarto** [comment]
@moinism Running BotUI (current HEAD) and Vue v2.5.17, I get exactly the same error as is described in this issue. Is there a known workaround?

(I'm using the most recent HEAD of BotUI because the npm version 0.3.4 is broken regarding the `select` action).
