### ISSUE TITLE
index.html:622 Uncaught (in promise) TypeError: botui.action.select is not a function     

### ISSUE THREAD

**Issue by zepili** [botui/botui#65]
Am testing the botui.action.select .

tried using the sample from the site or my version (which inspired from the sample) but it fails.

any idea  on how to fix? (I don't have a local repository)

Thanks 

in my index.html I have:

8< 8< 8< snip 8< 8< 8< 8< 8< 8< 8<
      <script src="https://unpkg.com/botui/build/botui.min.js"></script>
      <script src="https://unpkg.com/botui/build/botui.js"></script>
      <script src="https://cdn.jsdelivr.net/vue/latest/vue.min.js"></script>
8< 8< 8< snip 8< 8< 8< 8< 8< 8< 8<

when it reach the following the error is raised (chrome)

        var askNbrPlace = function(){
                botui.message.add({
                    delay: 1000,
                    content: "Pour quel jour??"
                    }).then(function (){
                botui.action.select({
                    action: {
                    placeholder : "Nombre de convives", 
                    value: 2,
                    searchselect : true,
                    label : 'text',
                    options : [
                        {value: "un" , text : "1 Personne" },
                        {value: "deux", text : "2 Personnes" },
                        {value: "trois", text : "3" },
                        {value: "quatre", text : "4" },
                        {value: "cinq", text : "5" },
                        {value: "six", text : "6" },
                                ],
                    button: {
                    icon: 'check',
                    label: 'OK'}
                    }
                    }).then(function(res) { 
                botui.message.add({
                    delay: 1000,
                    content: 'Nous serons ' + res.value
                    });
                        }); 
                            });
                                }

**Comment by zepili** [comment]
Am using the version from there : https://unpkg.com/botui/build/botui.min.js

any idea how to fix? 

is there another version with a fix publicly available ?

**Comment by yipcma** [comment]
@zepili  same issue here. Any news?

**Comment by moinism** [comment]
@zepili, @yipcma, the select function is available in the latest BotUI. Please check the version you are using.

**Comment by yipcma** [comment]
latest version on cdn is 
`<script src="https://unpkg.com/botui@0.3.4/build/botui.min.js"></script>`
which has no select, as in #68

**Comment by drbarto** [comment]
@moinism Any news on the `select` feature? I could really use this :) Really enjoying your library, good work!

**Comment by drbarto** [comment]
@moinism the current npm release (0.3.4) seems broken, it contains older code (which does not yet comprise `select`). As you said, the feature is in the current HEAD and when installing it manually or via CDN it works.

**Comment by moinism** [comment]
It should be available in the current build.
