### ISSUE TITLE
The SRC code is compiled.

### ISSUE THREAD

**Issue by ElCuboNegro** [botui/botui#69]
The source code is compiled and this difficult a lot the comunity endeavor.

**Comment by moinism** [comment]
How do you mean? The [source](https://github.com/botui/botui/blob/master/src/scripts/botui.js) is not compiled, only the build is.

**Comment by ElCuboNegro** [comment]
source structure is too complex, and everything is in a single file.

**Comment by TakesTheBiscuit** [comment]
https://github.com/botui/botui/blob/master/src/scripts/botui.js
