### ISSUE TITLE
Invalid parameter "searchselect" of "botui.action.select".

### ISSUE THREAD

**Issue by tacoyaky** [botui/botui#70]
Hi.
I cannot use the standart dropdown (not searchable select).
Even if I set "true" or "false" to parameter "searchselect: ", the result is the same.
It returns the result of "true".

I am using BotUI v0.3.4 in GitHub.

Please confirm.
Thank you.

**Comment by moinism** [comment]
@tacoyaky Please use `0.3.5`. Should be fixed.
