### ISSUE TITLE
botui.action.select not doing anything

### ISSUE THREAD

**Issue by averykohhc** [botui/botui#75]
Before updating my botui.js and css files, I had the error saying no such function available.

After I have updated my botui.js, botui.min.js, botui.min.css and botui-theme-default.css files according to the local repo from the 'build' folder, the error went away. But nothing happens when this code is run:

botui.action.select({
  action: {
      placeholder : "Select Language",
      value: 'TR', // Selected value or selected object. Example: {value: "TR", text : "Türkçe" }
      searchselect : true, // Default: true, false for standart dropdown
      label : 'text', // dropdown label variable
      options : [
                      {value: "EN", text : "English" },
                      {value: "ES", text : "Español" },
                      {value: "TR", text : "Türkçe" },
                      {value: "DE", text : "Deutsch" },
                      {value: "FR", text : "Français" },
                      {value: "IT", text : "Italiano" },
                ],
      button: {
        icon: 'check',
        label: 'OK'
      }
    }
}).then(function (res) { // will be called when a button is clicked.
  console.log(res.value); // will print "one" from 'value'
});

It just seemingly skips this section of code onto other code to display other messages through the botui.message.add function which works fine. 

Could you please let me know what I'm doing wrong?

**Comment by moinism** [comment]
@averykohhc the new release should fix it.
