### ISSUE TITLE
Adding icon on bot replies

### ISSUE THREAD

**Issue by andrelcalves** [botui/botui#81]
Hi there,
I'm trying to add an icon for when the bot replies to the user. I've looked through the CSS and index.html
The idea is to give the a bot an avatar and show it when the bot reply.

**Comment by moinism** [comment]
Changing source is not needed @ekoz.
You can just do:
```
botui.message.add({
  photo: true,
  content: 'Hello World!'
 });
```

Thanks for replying though!

> `profil` is going to be changed to `profile` in the next version. `profil` would be still be kept for backward compatibility.

**Comment by ekoz** [comment]
Could the human avatar be customized, such as being passed in as a parameter?
```
botui.message.add({
    human: true,
    photo: true,
    photo_path: '/imgs/human-avatar.png',
    content: 'Hello World from human!'
})
```

**Comment by ekoz** [comment]
thanks! @moinism

**Comment by nvp18** [comment]
botui.message.bot({

                    loading:true,
                    photo: '/static/images/fred.jpg',
                    delay:1000,
                    content:resp.data
            })

i have tried this in my django application but i is not working can you help me

**Comment by chinsinba** [comment]
is there any limitations on the required size of the image? For some reason, the image is not loading in the avatar. I have checked the images are present in the location and i could inspect and see it.

**Comment by sikandarchishty** [comment]
Hi, the image isn't loading (https://prnt.sc/t1q6sr). I'm using a png 64x64.
Only when I right click and select "load image" it loads the image (https://prnt.sc/t1q74b).

**Comment by DeshanFernando** [comment]
Hi I have the same issue the image is not loading even though it exists in the given path. Can someone address this issue. Highly appreciate.
