### ISSUE TITLE
How to display the conversational history from the last session?

### ISSUE THREAD

**Issue by parthsharma1996** [botui/botui#85]
I am using the Bot-UI framework for a mental health chat-bot. 

The issue I am currently facing is that of resuming the chat from the point where it was left off.  I am storing the chat history of each session at the server side, but I am not sure how to populate the chat window with the history of the conversation using BotUI each time the user visits again.

BotUI only seems to provide a `.add` function which I can use to populate the bot side of the conversation by calling it repeatedly, but how do I artificially populate the user side of the conversation using the conversational history that I have? I couldn't find a structured way of accomplishing this using BotUI. 

Am I missing something? What would be the best way to implement this?

**Comment by TakesTheBiscuit** [comment]
I'm not adequately qualified to answer you fully so this is a little anecdotal;

You could stash the answers using local storage / paired with server side.

When reloading you could fairly easily make a 'playback' script which would take key value pairs and fill the form one entry at a time before or after botui has instantiated - not sure if botui reads 'value=x' when it boots up, if so great, if not just have the underlying form be populated once it's ready 

Seems a bit like a hack but botui is built on wrapping a HTML form into conversation therefore refilling the form data in my mind makes most sense?

From a technical level then I guess it's answer recall using a session ID or cookie - to bring back the right answers 

Thoughts?

**Comment by moinism** [comment]
Unfortunately, @parthsharma1996 the only way to achieve that would be repeated calls to `.add`. In the future maybe we can think of an easier/simpler way.
