### ISSUE TITLE
Displaying charts in the conversation 

### ISSUE THREAD

**Issue by raoadnankhan** [botui/botui#99]
I would like to generate a line or histogram chart (on the client side) and display it in the botui container. Has anyone done this or similar to this? 

Any help is much appreciated .

**Comment by raoadnankhan** [comment]
I was thinking that I can put html and JS code as content, however, it is not showing up. Here is the code:

`return botui.message.add({
          delay: 300,
          cssClass: 'regular-text',
          loading: true,
          photo: true,
          type: 'html',
          content: "<div id=\"myDiv\" style=\"width: 230px; height: 300px;\"></div><script src="https://cdn.plot.ly/plotly-latest.min.js"></script><script>var trace1 = { x: ['Trial 1', 'Trial 2', 'Trial 3'], y: [3, 6, 4], name: 'Control', error_y: { type: 'data', array: [1, 0.5, 1.5], visible: true}, type: 'bar'}; var data = [trace1]; var layout = {barmode: 'group'}; Plotly.newPlot('myDiv', data, layout);</script>"
        })`
However, the bot ui widget is not displaying.. same code works if I save it in a separate file.

**Comment by raoadnankhan** [comment]
I was able to resolve this by adding a new message type `graph`. I am loading the plot JS using `loadScript` and then execute my script using `call()` method inside the Promise cb function. 

Structurally, I based it off of `update` implementation, as the `<div>` is defined and passed as message content and need to be updated in the cb function.

**Comment by tonysinghmss** [comment]
How did you add a new type `graph`? Can you share the code?
